[build]
  base = "https://github.com/antudev/trenzas-laplata"  # Ruta al directorio de  proyecto Flask
  command = "source env/bin/activate && pip install -r requirements.txt && python app.py"  # Comando para construir proyecto
  publish = "https://github.com/antudev/trenzas-laplata/tree/main/static"  # Ruta al directorio que contiene archivos estáticos