[build]
  base = "."
  command = "pip install -r requirements.txt && python app.py"
  publish = "./static"

[context.production]
  command = "pip install -r requirements.txt && python app.py"

[context.deploy-preview]
  command = "pip install -r requirements.txt && python app.py"

